### ISSUE TITLE
MuxLive encountered an error, Server timeout

### ISSUE THREAD

**Issue by royherma** [muxinc/example-ios-live-streaming#5]
Getting this when entering a random "stream key". 

Can you please explain where these stream keys can be retrieved via our account page, and if there is a need to change the sever url anywhere to successfully stream?

Thanks

**Comment by jsanford8** [comment]
Hi @royherma - sorry for the long delay here. You can get a live stream key by creating a live stream at https://dashboard.mux.com, and then in the left nav click on Live Streams. Once there, there should be a button to create a live stream.

Here's also a guide: https://docs.mux.com/docs/live-streaming.

Feel free to re-open this issue if you're still having issues.
