### ISSUE TITLE
Is this in active development?

### ISSUE THREAD

**Issue by jonchoi** [muxinc/example-ios-live-streaming#9]

**Comment by mmcc** [comment]
It's just intended to be an example, so while I wouldn't say it's _actively_ developed, we want to make sure it stays useful. Is there something specific you had in mind?

**Comment by dylanjha** [comment]
@jonchoi I have a PR here that updated this project to get it working with the latest tooling https://github.com/muxinc/example-ios-live-streaming/pull/11

If you're still interested feel free to pull down my branch and try it out. Feel free to re-open this issue if you have any more comments/questions
